name: the_parker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
  # sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^1.0.3+2
  eva_icons_flutter: ^2.0.0
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.19+2
  geolocator: ^5.0.1
  flutter_bloc: ^0.21.0
  equatable: ^0.6.0
  http: ^0.12.0+2
  custom_radio_grouped_button: ^1.0.0
  flutter_vector_icons: ^0.2.0
  extended_navbar_scaffold: ^1.0.1
  mapbox_search: ^1.0.2
  flutter_map: ^0.7.0+2
  flare_flutter: ^1.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/K2D-Light.ttf
          weight: 300
        - asset: assets/fonts/K2D-Regular.ttf
          weight: 400
        - asset: assets/fonts/K2D-Medium.ttf
          weight: 500
        - asset: assets/fonts/K2D-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/K2D-Bold.ttf
          weight: 700
        - asset: assets/fonts/K2D-ExtraBold.ttf
          weight: 900
